<?php
// This file was generated by stechec2-generator. DO NOT EDIT.


// Les 7 geisha (2, 2, 2, 3, 3, 4, 5)
define('NB_GEISHA', 7);

// Le nombre total de cartes (2 + 2 + 2 + 3 + 3 + 4 + 5)
define('NB_CARTES_TOTAL', 21);

// Le nombre de cartes que chaque personne a au début
define('NB_CARTES_DEBUT', 6);

// Le nombre de cartes écartées au début du jeu
define('NB_CARTES_ECARTEES', 1);

// Le nombre total d'action que chaque joueur devra faire
define('NB_ACTIONS', 4);

// Le nombre total de manches avant la fin de la partie
define('NB_MANCHES_MAX', 3);

// La valeur (et le nombre de cartes) de chaque geisha séparée par des |
define('GEISHA_VALEUR', "2|2|2|3|3|4|5");



// Les actions de jeu
define('VALIDER', 0);  // Valide une unique carte
define('DEFAUSSER', 1);  // Defausse deux cartes
define('CHOIX_TROIS', 2);  // Donne le choix entre trois cartes
define('CHOIX_PAQUETS', 3);  // Donne le choix entre deux paquets de deux cartes
define('PREMIER_JOUEUR', 4);  // Aucune action n'a été jouée (utilisé dans tour_precedent)

// Enumeration contentant toutes les erreurs possibles
define('OK', 0);  // pas d'erreur
define('ACTION_DEJA_JOUEE', 1);  // l'action a déjà été jouée
define('CARTES_INVALIDES', 2);  // vous ne pouvez pas jouer ces cartes
define('PAQUET_INVALIDE', 3);  // ce paquet n'existe pas
define('GEISHA_INVALIDES', 4);  // cette geisha n'existe pas (doit être un entier entre 0 et NB_GEISHA)
define('JOUEUR_INVALIDE', 5);  // ce joueur n'existe pas
define('CHOIX_INVALIDE', 6);  // vous ne pouvez pas repondre à ce choix
define('ACTION_INVALIDE', 7);  // vous ne pouvez pas jouer cette action maintenant

// Enumeration représentant les différents joueurs
define('JOUEUR_1', 0);  // Le joueur 1
define('JOUEUR_2', 1);  // Le joueur 2
define('EGALITE', 2);  // Égalité, utilisé uniquement dans possession_geisha
