-- This file was generated by stechec2-generator. DO NOT EDIT.

module Api (
Action (..),
Error (..),
Joueur (..),

Action_jouee (..),

id_joueur,
id_adversaire,
manche,
tour,
tour_precedent,
nb_carte_validee,
possession_geisha,
est_jouee_action,
nb_cartes,
cartes_en_main,
carte_pioche,
action_valider,
action_defausser,
action_choix_trois,
action_choix_paquets,
repondre_choix_trois,
repondre_choix_paquets,
afficher_action,
afficher_error,
afficher_joueur,
afficher_action_jouee,

nb_geisha,
nb_cartes_total,
nb_cartes_debut,
nb_cartes_ecartees,
nb_actions,
nb_manches_max,
geisha_valeur,
) where

import CApi


-- Les 7 geisha (2, 2, 2, 3, 3, 4, 5)
nb_geisha :: Int
nb_geisha = 7

-- Le nombre total de cartes (2 + 2 + 2 + 3 + 3 + 4 + 5)
nb_cartes_total :: Int
nb_cartes_total = 21

-- Le nombre de cartes que chaque personne a au début
nb_cartes_debut :: Int
nb_cartes_debut = 6

-- Le nombre de cartes écartées au début du jeu
nb_cartes_ecartees :: Int
nb_cartes_ecartees = 1

-- Le nombre total d'action que chaque joueur devra faire
nb_actions :: Int
nb_actions = 4

-- Le nombre total de manches avant la fin de la partie
nb_manches_max :: Int
nb_manches_max = 3

-- La valeur (et le nombre de cartes) de chaque geisha séparée par des |
geisha_valeur :: String
geisha_valeur = "2|2|2|3|3|4|5"
